// AUTO-GENERATED by src/libs/i18n/scripts/generate-keys.ts.
// Do not edit manually — run `bun run i18n:keys` to regenerate.

export type TranslationKey =
	| "auth.accessDeniedPermission"
	| "auth.accessDeniedRole"
	| "auth.accessDeniedSuperuser"
	| "auth.accountInactive"
	| "auth.authRequired"
	| "auth.emailAlreadyInUse"
	| "auth.emailAlreadyRegistered"
	| "auth.emailAlreadyVerified"
	| "auth.emailNotVerified"
	| "auth.emailVerified"
	| "auth.forgotPasswordSent"
	| "auth.invalidCredentials"
	| "auth.invalidRefreshToken"
	| "auth.invalidResetToken"
	| "auth.invalidToken"
	| "auth.invalidTokenType"
	| "auth.invalidUserId"
	| "auth.invalidVerificationToken"
	| "auth.loginSuccess"
	| "auth.passwordReset"
	| "auth.refreshTokenRevoked"
	| "auth.registerSuccess"
	| "auth.resendVerificationSent"
	| "auth.tokenRefreshed"
	| "auth.userNotFound"
	| "auth.validationError"
	| "common.apiRunning"
	| "common.created"
	| "common.deleted"
	| "common.fetched"
	| "common.retrieved"
	| "common.success"
	| "common.updated"
	| "errors.badRequest"
	| "errors.conflict"
	| "errors.forbidden"
	| "errors.internal"
	| "errors.notFound"
	| "errors.parseBody"
	| "errors.parseFailed"
	| "errors.payloadTooLarge"
	| "errors.routeNotFound"
	| "errors.tooManyRequests"
	| "errors.unauthorized"
	| "errors.unprocessableEntity"
	| "errors.unsupportedMediaType"
	| "health.allHealthy"
	| "health.someUnhealthy"
	| "mail.subject.resetPassword"
	| "mail.subject.verification"
	| "profile.currentPasswordIncorrect"
	| "profile.passwordUpdated"
	| "profile.retrieved"
	| "profile.updated"
	| "settings.permissions.created"
	| "settings.permissions.deleted"
	| "settings.permissions.detailFetched"
	| "settings.permissions.fetched"
	| "settings.permissions.updated"
	| "settings.roles.created"
	| "settings.roles.deleted"
	| "settings.roles.detailFetched"
	| "settings.roles.fetched"
	| "settings.roles.invalidPermissions"
	| "settings.roles.updated"
	| "settings.select.permissionsFetched"
	| "settings.select.rolesFetched"
	| "settings.users.created"
	| "settings.users.deleted"
	| "settings.users.detailFetched"
	| "settings.users.emailExists"
	| "settings.users.fetched"
	| "settings.users.invalidRoles"
	| "settings.users.passwordChanged"
	| "settings.users.updated"
	| "validation.expectedArray"
	| "validation.expectedBoolean"
	| "validation.expectedDateTime"
	| "validation.expectedEmail"
	| "validation.expectedNumber"
	| "validation.expectedObject"
	| "validation.expectedString"
	| "validation.expectedUuid"
	| "validation.failed"
	| "validation.invalid"
	| "validation.patternMismatch"
	| "validation.required"
	| "validation.tooLarge"
	| "validation.tooLong"
	| "validation.tooShort"
	| "validation.tooSmall";

export const TRANSLATION_KEYS: ReadonlySet<TranslationKey> =
	new Set<TranslationKey>([
		"auth.accessDeniedPermission",
		"auth.accessDeniedRole",
		"auth.accessDeniedSuperuser",
		"auth.accountInactive",
		"auth.authRequired",
		"auth.emailAlreadyInUse",
		"auth.emailAlreadyRegistered",
		"auth.emailAlreadyVerified",
		"auth.emailNotVerified",
		"auth.emailVerified",
		"auth.forgotPasswordSent",
		"auth.invalidCredentials",
		"auth.invalidRefreshToken",
		"auth.invalidResetToken",
		"auth.invalidToken",
		"auth.invalidTokenType",
		"auth.invalidUserId",
		"auth.invalidVerificationToken",
		"auth.loginSuccess",
		"auth.passwordReset",
		"auth.refreshTokenRevoked",
		"auth.registerSuccess",
		"auth.resendVerificationSent",
		"auth.tokenRefreshed",
		"auth.userNotFound",
		"auth.validationError",
		"common.apiRunning",
		"common.created",
		"common.deleted",
		"common.fetched",
		"common.retrieved",
		"common.success",
		"common.updated",
		"errors.badRequest",
		"errors.conflict",
		"errors.forbidden",
		"errors.internal",
		"errors.notFound",
		"errors.parseBody",
		"errors.parseFailed",
		"errors.payloadTooLarge",
		"errors.routeNotFound",
		"errors.tooManyRequests",
		"errors.unauthorized",
		"errors.unprocessableEntity",
		"errors.unsupportedMediaType",
		"health.allHealthy",
		"health.someUnhealthy",
		"mail.subject.resetPassword",
		"mail.subject.verification",
		"profile.currentPasswordIncorrect",
		"profile.passwordUpdated",
		"profile.retrieved",
		"profile.updated",
		"settings.permissions.created",
		"settings.permissions.deleted",
		"settings.permissions.detailFetched",
		"settings.permissions.fetched",
		"settings.permissions.updated",
		"settings.roles.created",
		"settings.roles.deleted",
		"settings.roles.detailFetched",
		"settings.roles.fetched",
		"settings.roles.invalidPermissions",
		"settings.roles.updated",
		"settings.select.permissionsFetched",
		"settings.select.rolesFetched",
		"settings.users.created",
		"settings.users.deleted",
		"settings.users.detailFetched",
		"settings.users.emailExists",
		"settings.users.fetched",
		"settings.users.invalidRoles",
		"settings.users.passwordChanged",
		"settings.users.updated",
		"validation.expectedArray",
		"validation.expectedBoolean",
		"validation.expectedDateTime",
		"validation.expectedEmail",
		"validation.expectedNumber",
		"validation.expectedObject",
		"validation.expectedString",
		"validation.expectedUuid",
		"validation.failed",
		"validation.invalid",
		"validation.patternMismatch",
		"validation.required",
		"validation.tooLarge",
		"validation.tooLong",
		"validation.tooShort",
		"validation.tooSmall",
	]);
