/* eslint-disable no-console */
import fs from "node:fs";
import path from "node:path";

type Dictionary = Record<string, string>;

const localesDir = path.join(import.meta.dir, "..", "locales");
const sourceLocale = "en";
const sourcePath = path.join(localesDir, `${sourceLocale}.json`);
const outputPath = path.join(localesDir, "keys.generated.ts");

const readDictionary = (file: string): Dictionary => {
	const raw = fs.readFileSync(file, "utf-8");
	return JSON.parse(raw) as Dictionary;
};

const source = readDictionary(sourcePath);
const sourceKeys = Object.keys(source).sort();

const otherFiles = fs
	.readdirSync(localesDir)
	.filter((f) => f.endsWith(".json") && f !== `${sourceLocale}.json`);

let hasIssues = false;
for (const file of otherFiles) {
	const locale = path.basename(file, ".json");
	const dict = readDictionary(path.join(localesDir, file));
	const dictKeys = new Set(Object.keys(dict));

	const missing = sourceKeys.filter((k) => !dictKeys.has(k));
	const extra = [...dictKeys].filter((k) => !sourceKeys.includes(k));

	if (missing.length) {
		hasIssues = true;
		console.error(
			`[i18n] ${locale}.json is missing ${missing.length} key(s):\n  - ${missing.join("\n  - ")}`,
		);
	}
	if (extra.length) {
		console.warn(
			`[i18n] ${locale}.json has ${extra.length} key(s) not in ${sourceLocale}.json:\n  - ${extra.join("\n  - ")}`,
		);
	}
}

const banner = `// AUTO-GENERATED by src/libs/i18n/scripts/generate-keys.ts.
// Do not edit manually — run \`bun run i18n:keys\` to regenerate.

`;

const unionBody = `export type TranslationKey =\n${sourceKeys
	.map((k) => `\t| ${JSON.stringify(k)}`)
	.join("\n")};\n`;

const setBody = `\nexport const TRANSLATION_KEYS: ReadonlySet<TranslationKey> = new Set<TranslationKey>([\n${sourceKeys
	.map((k) => `\t${JSON.stringify(k)},`)
	.join("\n")}\n]);\n`;

fs.writeFileSync(outputPath, banner + unionBody + setBody);

console.log(
	`[i18n] Generated ${sourceKeys.length} translation keys → ${path.relative(process.cwd(), outputPath)}`,
);

if (hasIssues) {
	console.error("[i18n] One or more locale files are missing keys.");
	process.exit(1);
}
